version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.4
    - 2.8.1
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: flynt
    versions:
    - "0.60"
    - "0.61"
    - "0.63"
  - dependency-name: dask
    versions:
    - 2021.1.1
    - 2021.2.0
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: click-loguru
    versions:
    - 1.3.5
